# Generated by Django 3.0.7 on 2021-01-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_img',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='DEFAULT VALUE', max_length=70, null=True, unique=True),
        ),
    ]
