# Generated by Django 3.0.7 on 2021-02-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210210_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(default=False, upload_to='pics'),
        ),
    ]
