# Generated by Django 3.0.7 on 2021-03-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20210222_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
